In [1]:
import numpy as np
import pandas as pd

In [2]:
credits=pd.read_csv('tmdb_5000_credits.csv')
movies=pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
movies.head(1)['genres'].values

array(['[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'],
      dtype=object)

In [5]:
#merge both datasets
movies=movies.merge(credits,on="title")

In [6]:
movies.shape

(4809, 23)

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [8]:
#columns needs to consider
#genres
#id
#keywords
#overview
#title
#cast
#crew
movies=movies[['id','title','overview','keywords','genres','cast','crew']]

In [9]:
movies.head(1)

,id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
movies.isnull().sum()            #for missing values

id          0
title       0
overview    3
keywords    0
genres      0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):   #convert obj that is in string to list so we can access it
        #through the library of ast and the function literal_eval
        L.append(i['name'])
    return L

In [14]:
movies['genres']=movies['genres'].apply(convert)

In [15]:
movies.head(1)

,id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [16]:
movies['keywords']=movies['keywords'].apply(convert)

In [17]:
#in cast data we want top 3 dictionaries of each movie
#in each dictionary there is a all info of one cast member(actor) so we want to fetch their name

In [18]:
import ast
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):   #convert obj that is in string to list so we can access it
        #through the library of ast and the function literal_eval
        if(counter!=3):
           L.append(i['name'])
           counter+=1
        else:
           break
    return L

In [19]:
movies['cast']=movies['cast'].apply(convert3)

In [20]:
import ast
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):   #convert obj that is in string to list so we can access it
        #through the library of ast and the function literal_eval
        if(i['job']=='director'):
          L.append(i['name'])
          break
    return L

In [21]:
movies['crew']=movies['crew'].apply(fetch_director)

In [22]:
#convert overview from string to list
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [23]:
#remove space between one entity ..so that system willnot confuse with same first named entity
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])   
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [24]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [25]:
new_df=movies[['id','title','tags']]

In [26]:
new_df

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [27]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_13423/487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [28]:
new_df.head(1)

      id   title                                               tags
0  19995  Avatar  In the 22nd century, a paraplegic Marine is di...

In [29]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver'

In [30]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_13423/4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [31]:
import sys
print(sys.executable)

/anaconda/envs/azureml_py310_sdkv2/bin/python

In [32]:
import sys
!{sys.executable} -m pip install nltk

Requirement already satisfied: nltk in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (3.9.1)
Requirement already satisfied: click in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from nltk) (4.67.1)

In [33]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [34]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [35]:
new_df['tags']=new_df['tags'].apply(stem)

/tmp/ipykernel_13423/3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

## Text vectorization

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [37]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [38]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [40]:
features = cv.get_feature_names_out()
print(features[:100])  # First 100 words

['000' '007' '10' '100' '11' '12' '13' '14' '15' '16' '17' '17th' '18'
 '18th' '18thcenturi' '19' '1910' '1920' '1930' '1940' '1944' '1950'
 '1950s' '1960' '1960s' '1970' '1970s' '1971' '1974' '1976' '1980' '1985'
 '1990' '1999' '19th' '19thcenturi' '20' '200' '2003' '2009' '20th' '21st'
 '23' '24' '25' '30' '300' '3d' '40' '50' '500' '60' '70' '80' 'aaron'
 'aaroneckhart' 'abandon' 'abbi' 'abduct' 'abigailbreslin' 'abil' 'abl'
 'aboard' 'abov' 'abus' 'academ' 'academi' 'accept' 'access' 'accid'
 'accident' 'acclaim' 'accompani' 'accomplish' 'account' 'accus' 'ace'
 'achiev' 'acquaint' 'act' 'action' 'actionhero' 'activ' 'activist'
 'activities' 'actor' 'actress' 'actual' 'ad' 'adam' 'adamsandl' 'adapt'
 'add' 'addict' 'adjust' 'admir' 'admit' 'adolesc' 'adopt' 'ador']

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
similarity=cosine_similarity(vectors) #calculating cosine distance between each vector-->less angle ->more similarity 
#cosine angle that is more with similar movies

In [49]:
cosine_similarity(vectors).shape  #as distance of each movie with every other movie

(4806, 4806)

In [51]:
#we need to hold the indexes in data so that after sorting ,if index is not there prediction may be wrong
#use enumerate ()
list(enumerate(similarity[0]))

[(0, 0.9999999999999998),
 (1, 0.08585457105482137),
 (2, 0.08718572905786445),
 (3, 0.07494001345079687),
 (4, 0.1898315991504998),
 (5, 0.11083777463036817),
 (6, 0.03958262466638396),
 (7, 0.1487044791289829),
 (8, 0.06003002251876642),
 (9, 0.09913631941932194),
 (10, 0.10529962529853128),
 (11, 0.09695723311274393),
 (12, 0.09320546490018),
 (13, 0.04604092555161308),
 (14, 0.1316245316231641),
 (15, 0.06367145399670132),
 (16, 0.07897471897389846),
 (17, 0.14165281524036175),
 (18, 0.09687303228651607),
 (19, 0.08489527199560176),
 (20, 0.05881716976750462),
 (21, 0.11115400287534567),
 (22, 0.0685591170191061),
 (23, 0.09004503377814962),
 (24, 0.05479966243511909),
 (25, 0.03465834966066909),
 (26, 0.15404884978892902),
 (27, 0.18944220058835154),
 (28, 0.11810771907149853),
 (29, 0.06420877537090426),
 (30, 0.06839411288813299),
 (31, 0.16120647005479025),
 (32, 0.08710071126186844),
 (33, 0.10067340828210367),
 (34, 0.0),
 (35, 0.10283867552865913),
 (36, 0.1754942736973651),
 (37, 0.08108108108108109),
 (38, 0.08156473902861858),
 (39, 0.07897471897389846),
 (40, 0.07798128673650545),
 (41, 0.16967515794730187),
 (42, 0.0),
 (43, 0.09208185110322616),
 (44, 0.03504998186163908),
 (45, 0.08351476906593233),
 (46, 0.14309095175803563),
 (47, 0.199363055707225),
 (48, 0.0863465783552691),
 (49, 0.059053859535749265),
 (50, 0.11624763874381927),
 (51, 0.08094446585163528),
 (52, 0.15042366316917008),
 (53, 0.04393747751637468),
 (54, 0.03163859985841663),
 (55, 0.0713262951621492),
 (56, 0.14019992744655632),
 (57, 0.024507154069793594),
 (58, 0.06906138832741962),
 (59, 0.07398532461669939),
 (60, 0.018735003362699218),
 (61, 0.23490461932490855),
 (62, 0.08489527199560176),
 (63, 0.08219949365267865),
 (64, 0.030528125543633176),
 (65, 0.0199363055707225),
 (66, 0.02279803762937766),
 (67, 0.16439898730535726),
 (68, 0.12427395320024),
 (69, 0.026936179620310644),
 (70, 0.07798128673650545),
 (71, 0.07521183158458504),
 (72, 0.1389425035941821),
 (73, 0.03427955850955305),
 (74, 0.2071841649822589),
 (75, 0.10529962529853128),
 (76, 0.07271792483455794),
 (77, 0.014363606211965715),
 (78, 0.051987524491003634),
 (79, 0.06367145399670132),
 (80, 0.05114214254947678),
 (81, 0.11168711865749101),
 (82, 0.07702442489446452),
 (83, 0.1823843010350213),
 (84, 0.12527215359889848),
 (85, 0.11565903932254226),
 (86, 0.07194017065667525),
 (87, 0.11277677488692017),
 (88, 0.09158437663089954),
 (89, 0.058123819371909635),
 (90, 0.06327719971683327),
 (91, 0.17170914210964275),
 (92, 0.06263607679944924),
 (93, 0.07194017065667525),
 (94, 0.1898315991504998),
 (95, 0.1438803413133505),
 (96, 0.07897471897389846),
 (97, 0.07045670884515312),
 (98, 0.07702442489446452),
 (99, 0.027399831217559546),
 (100, 0.07009996372327816),
 (101, 0.07798128673650545),
 (102, 0.12629480039223434),
 (103, 0.08156473902861858),
 (104, 0.05723638070321425),
 (105, 0.10514994558491725),
 (106, 0.06314740019611717),
 (107, 0.06213697660011999),
 (108, 0.14704292441876157),
 (109, 0.06575959492214292),
 (110, 0.04604092555161308),
 (111, 0.15404884978892902),
 (112, 0.07897471897389846),
 (113, 0.04393747751637468),
 (114, 0.04697113923010208),
 (115, 0.04474373701426829),
 (116, 0.048478616556371965),
 (117, 0.06105625108726635),
 (118, 0.034094761699651185),
 (119, 0.04433510985214727),
 (120, 0.0),
 (121, 0.1144727614064285),
 (122, 0.11810771907149853),
 (123, 0.11290968804428622),
 (124, 0.06711560552140243),
 (125, 0.07702442489446451),
 (126, 0.13513513513513514),
 (127, 0.148916158209988),
 (128, 0.0),
 (129, 0.09491579957524991),
 (130, 0.027399831217559546),
 (131, 0.106676149412533),
 (132, 0.04559607525875532),
 (133, 0.029061909685954818),
 (134, 0.13151918984428584),
 (135, 0.0),
 (136, 0.023728949893812478),
 (137, 0.030528125543633176),
 (138, 0.1316245316231641),
 (139, 0.12234710854292788),
 (140, 0.04604092555161308),
 (141, 0.0885807893036239),
 (142, 0.08585457105482137),
 (143, 0.08787495503274936),
 (144, 0.050734628943184104),
 (145, 0.01964943729729648),
 (146, 0.016522719903220323),
 (147, 0.056388387443460086),
 (148, 0.09672388203287416),
 (149, 0.15719549837837185),
 (150, 0.17199894677510616),
 (151, 0.21029989116983447),
 (152, 0.08458258116519013),
 (153, 0.07974522228289),
 (154, 0.06213697660012),
 (155, 0.02054987341316966),
 (156, 0.06070834938872646),
 (157, 0.10514994558491723),
 (158, 0.13549162565314346),
 (159, 0.06575959492214292),
 (160, 0.11869522585912262),
 (161, 0.03224129401095805),
 (162, 0.03427955850955305),
 (163, 0.051987524491003634),
 (164, 0.08219949365267865),
 (165, 0.04697113923010208),
 (166, 0.12683657235796025),
 (167, 0.09004503377814962),
 (168, 0.17757120130114434),
 (169, 0.08948747402853657),
 (170, 0.10793322294408637),
 (171, 0.02302046277580654),
 (172, 0.20567735105731827),
 (173, 0.023728949893812478),
 (174, 0.07897471897389846),
 (175, 0.07271792483455794),
 (176, 0.029526929767874632),
 (177, 0.0),
 (178, 0.025070610528195012),
 (179, 0.07352146220938077),
 (180, 0.022581937608857246),
 (181, 0.04559607525875532),
 (182, 0.1186447494690624),
 (183, 0.0713262951621492),
 (184, 0.17757120130114434),
 (185, 0.051987524491003634),
 (186, 0.06025359879550432),
 (187, 0.15404884978892902),
 (188, 0.022581937608857246),
 (189, 0.1162476387438193),
 (190, 0.08561170049453902),
 (191, 0.04956815970966097),
 (192, 0.047960113771116836),
 (193, 0.07983920607777244),
 (194, 0.0),
 (195, 0.06105625108726635),
 (196, 0.051987524491003634),
 (197, 0.03771571432023571),
 (198, 0.058123819371909635),
 (199, 0.08867021970429453),
 (200, 0.11028219331407116),
 (201, 0.0),
 (202, 0.03163859985841663),
 (203, 0.08585457105482137),
 (204, 0.04956815970966097),
 (205, 0.07749842582921286),
 (206, 0.11241002017619531),
 (207, 0.07798128673650545),
 (208, 0.12655439943366653),
 (209, 0.0685591170191061),
 (210, 0.07702442489446452),
 (211, 0.025070610528195012),
 (212, 0.06774581282657174),
 (213, 0.06025359879550432),
 (214, 0.0),
 (215, 0.06711560552140243),
 (216, 0.06711560552140244),
 (217, 0.0863465783552691),
 (218, 0.039872611141445),
 (219, 0.09320546490018),
 (220, 0.18316875326179907),
 (221, 0.047960113771116836),
 (222, 0.08094446585163528),
 (223, 0.10529962529853128),
 (224, 0.061649620239508984),
 (225, 0.047457899787624956),
 (226, 0.03106848830006),
 (227, 0.08458258116519013),
 (228, 0.11185934253567072),
 (229, 0.10892898631973956),
 (230, 0.0930725988812425),
 (231, 0.0),
 (232, 0.1144727614064285),
 (233, 0.10283867552865913),
 (234, 0.08710071126186844),
 (235, 0.07610194341477616),
 (236, 0.11810771907149853),
 (237, 0.06711560552140244),
 (238, 0.11241002017619531),
 (239, 0.09248165577087425),
 (240, 0.047960113771116836),
 (241, 0.07897471897389846),
 (242, 0.08219949365267865),
 (243, 0.09491579957524991),
 (244, 0.09320546490018),
 (245, 0.08219949365267865),
 (246, 0.07749842582921286),
 (247, 0.0),
 (248, 0.04559607525875532),
 (249, 0.14019992744655632),
 (250, 0.0),
 (251, 0.04244763599780088),
 (252, 0.02054987341316966),
 (253, 0.06367145399670132),
 (254, 0.07045670884515312),
 (255, 0.0),
 (256, 0.11028219331407116),
 (257, 0.05479966243511909),
 (258, 0.01793740008335438),
 (259, 0.06213697660012),
 (260, 0.20668850837512243),
 (261, 0.024239308278185982),
 (262, 0.10887588907733556),
 (263, 0.10067340828210367),
 (264, 0.0),
 (265, 0.027788500718836418),
 (266, 0.10028244211278005),
 (267, 0.06711560552140244),
 (268, 0.0533380747062665),
 (269, 0.03001501125938321),
 (270, 0.09032775043542898),
 (271, 0.07194017065667525),
 (272, 0.028618190351607124),
 (273, 0.021402925123634755),
 (274, 0.09126381430107945),
 (275, 0.14763464883937316),
 (276, 0.0644825880219161),
 (277, 0.05413539955388112),
 (278, 0.11990028442779209),
 (279, 0.07118684968143743),
 (280, 0.0),
 (281, 0.06590621627456203),
 (282, 0.022581937608857246),
 (283, 0.028194193721730043),
 (284, 0.0186145197762485),
 (285, 0.01979131233319198),
 (286, 0.07916524933276792),
 (287, 0.02666903735313325),
 (288, 0.027788500718836418),
 (289, 0.04649905549752771),
 (290, 0.0644825880219161),
 (291, 0.050734628943184104),
 (292, 0.09004503377814962),
 (293, 0.03001501125938321),
 (294, 0.1453095484297741),
 (295, 0.106676149412533),
 (296, 0.03929887459459296),
 (297, 0.04516387521771449),
 (298, 0.0),
 (299, 0.06070834938872646),
 (300, 0.17348855898381338),
 (301, 0.09428928580058928),
 (302, 0.07118684968143743),
 (303, 0.028194193721730043),
 (304, 0.06689299925138306),
 (305, 0.1926263261127128),
 (306, 0.08219949365267865),
 (307, 0.11022596991336672),
 (308, 0.0685591170191061),
 (309, 0.06327719971683327),
 (310, 0.03106848830006),
 (311, 0.1522038868295523),
 (312, 0.10269923319261937),
 (313, 0.055577001437672836),
 (314, 0.0),
 (315, 0.08458258116519013),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.10283867552865913),
 (320, 0.03163859985841663),
 (321, 0.0),
 (322, 0.213352298825066),
 (323, 0.03001501125938321),
 (324, 0.024507154069793594),
 (325, 0.10067340828210367),
 (326, 0.058123819371909635),
 (327, 0.027788500718836418),
 (328, 0.027788500718836418),
 (329, 0.08000711205939975),
 (330, 0.10269923319261937),
 (331, 0.09119215051751065),
 (332, 0.10810810810810811),
 (333, 0.024784079854830485),
 (334, 0.09802861627917438),
 (335, 0.04697113923010208),
 (336, 0.07009996372327816),
 (337, 0.04604092555161308),
 (338, 0.0),
 (339, 0.04901430813958719),
 (340, 0.050734628943184104),
 (341, 0.08458258116519013),
 (342, 0.16542328997110672),
 (343, 0.019510570275964215),
 (344, 0.030528125543633176),
 (345, 0.02348556961505104),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06105625108726635),
 (349, 0.08000711205939975),
 (350, 0.04956815970966097),
 (351, 0.0),
 (352, 0.027788500718836418),
 (353, 0.04280585024726951),
 (354, 0.022167554926073633),
 (355, 0.037229039552497),
 (356, 0.09320546490018),
 (357, 0.0),
 (358, 0.06105625108726635),
 (359, 0.03163859985841663),
 (360, 0.021402925123634755),
 (361, 0.07702442489446452),
 (362, 0.09863939238321438),
 (363, 0.1011805823145441),
 (364, 0.023728949893812478),
 (365, 0.07702442489446452),
 (366, 0.056388387443460086),
 (367, 0.0),
 (368, 0.13151918984428584),
 (369, 0.12253577034896798),
 (370, 0.05134961659630968),
 (371, 0.09802861627917438),
 (372, 0.048478616556371965),
 (373, 0.17937400083354382),
 (374, 0.038482892144202245),
 (375, 0.06263607679944924),
 (376, 0.04697113923010208),
 (377, 0.0),
 (378, 0.0),
 (379, 0.05114214254947678),
 (380, 0.05264981264926564),
 (381, 0.08489527199560176),
 (382, 0.0),
 (383, 0.04393747751637468),
 (384, 0.029526929767874632),
 (385, 0.0),
 (386, 0.022371868507134143),
 (387, 0.024239308278185982),
 (388, 0.0),
 (389, 0.09158437663089954),
 (390, 0.02666903735313325),
 (391, 0.05733298225836872),
 (392, 0.030528125543633176),
 (393, 0.0),
 (394, 0.025367314471592052),
 (395, 0.05264981264926564),
 (396, 0.04474373701426829),
 (397, 0.05264981264926564),
 (398, 0.0),
 (399, 0.023980056885558418),
 (400, 0.09158437663089952),
 (401, 0.03287979746107146),
 (402, 0.07897471897389846),
 (403, 0.08419653359482289),
 (404, 0.06213697660012),
 (405, 0.056388387443460086),
 (406, 0.021049133398705722),
 (407, 0.021586644588817275),
 (408, 0.03287979746107146),
 (409, 0.0),
 (410, 0.09913631941932194),
 (411, 0.0533380747062665),
 (412, 0.09695723311274393),
 (413, 0.1453095484297741),
 (414, 0.03001501125938321),
 (415, 0.05413539955388112),
 (416, 0.051987524491003634),
 (417, 0.036760731104690386),
 (418, 0.03587480016670876),
 (419, 0.07045670884515312),
 (420, 0.1139901881468883),
 (421, 0.023728949893812478),
 (422, 0.11810771907149853),
 (423, 0.042098266797411445),
 (424, 0.03822198817224581),
 (425, 0.06532553344640132),
 (426, 0.05446449315986979),
 (427, 0.02702702702702703),
 (428, 0.056949479745149925),
 (429, 0.0),
 (430, 0.05134961659630968),
 (431, 0.024507154069793594),
 (432, 0.11510231387903269),
 (433, 0.03106848830006),
 (434, 0.0),
 (435, 0.03587480016670876),
 (436, 0.0),
 (437, 0.02632490632463282),
 (438, 0.12392039927415242),
 (439, 0.02702702702702703),
 (440, 0.023980056885558418),
 (441, 0.058123819371909635),
 (442, 0.04604092555161308),
 (443, 0.06532553344640132),
 (444, 0.0),
 (445, 0.10146925788636821),
 (446, 0.023728949893812478),
 (447, 0.06532553344640132),
 (448, 0.021586644588817275),
 (449, 0.11115400287534567),
 (450, 0.021402925123634755),
 (451, 0.025367314471592052),
 (452, 0.03106848830006),
 (453, 0.025070610528195012),
 (454, 0.11742784807525519),
 (455, 0.06213697660011999),
 (456, 0.04393747751637468),
 (457, 0.0885807893036239),
 (458, 0.04393747751637468),
 (459, 0.03504998186163908),
 (460, 0.024784079854830485),
 (461, 0.14309095175803563),
 (462, 0.03271662128033808),
 (463, 0.03287979746107146),
 (464, 0.0),
 (465, 0.0),
 (466, 0.14704292441876154),
 (467, 0.10701462561817378),
 (468, 0.028194193721730043),
 (469, 0.06070834938872646),
 (470, 0.04604092555161308),
 (471, 0.06475993376645182),
 (472, 0.10959932487023819),
 (473, 0.09491579957524991),
 (474, 0.0),
 (475, 0.04433510985214727),
 (476, 0.1371182340382122),
 (477, 0.0),
 (478, 0.05479966243511909),
 (479, 0.0891578689526865),
 (480, 0.09913631941932194),
 (481, 0.0),
 (482, 0.02196873875818734),
 (483, 0.1289651760438322),
 (484, 0.03106848830006),
 (485, 0.05405405405405406),
 (486, 0.08099356774626426),
 (487, 0.1289651760438322),
 (488, 0.06746792083200746),
 (489, 0.0),
 (490, 0.14349920066683505),
 (491, 0.10195592378577323),
 (492, 0.07702442489446452),
 (493, 0.03120812265889869),
 (494, 0.0),
 (495, 0.19344776406574832),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0685591170191061),
 (499, 0.0),
 (500, 0.02666903735313325),
 (501, 0.08284930213349333),
 (502, 0.13549162565314346),
 (503, 0.07610194341477615),
 (504, 0.0),
 (505, 0.1371182340382122),
 (506, 0.03504998186163908),
 (507, 0.26130213378560535),
 (508, 0.10397504898200727),
 (509, 0.022581937608857246),
 (510, 0.10028244211278005),
 (511, 0.0949157995752499),
 (512, 0.027788500718836418),
 (513, 0.15220388682955233),
 (514, 0.04956815970966097),
 (515, 0.025367314471592052),
 (516, 0.029061909685954818),
 (517, 0.0),
 (518, 0.04433510985214727),
 (519, 0.0),
 (520, 0.0),
 (521, 0.023980056885558418),
 (522, 0.024507154069793594),
 (523, 0.04956815970966097),
 (524, 0.0),
 (525, 0.047960113771116836),
 (526, 0.028618190351607124),
 (527, 0.03427955850955305),
 (528, 0.02279803762937766),
 (529, 0.1696751579473019),
 (530, 0.056388387443460086),
 (531, 0.047457899787624956),
 (532, 0.02122381799890044),
 (533, 0.06105625108726635),
 (534, 0.08787495503274936),
 (535, 0.09913631941932194),
 (536, 0.11399018814688831),
 (537, 0.0685591170191061),
 (538, 0.0),
 (539, 0.2537477434955704),
 (540, 0.07610194341477616),
 (541, 0.10887588907733554),
 (542, 0.037470006725398436),
 (543, 0.07194017065667525),
 (544, 0.056388387443460086),
 (545, 0.025367314471592052),
 (546, 0.0644825880219161),
 (547, 0.08458258116519013),
 (548, 0.0),
 (549, 0.12253577034896797),
 (550, 0.025070610528195012),
 (551, 0.03822198817224581),
 (552, 0.0),
 (553, 0.029526929767874632),
 (554, 0.0),
 (555, 0.04559607525875532),
 (556, 0.028194193721730043),
 (557, 0.12535305264097507),
 (558, 0.0),
 (559, 0.030528125543633176),
 (560, 0.036760731104690386),
 (561, 0.03287979746107146),
 (562, 0.03163859985841663),
 (563, 0.025993762245501817),
 (564, 0.09158437663089952),
 (565, 0.04355035563093422),
 (566, 0.024239308278185982),
 (567, 0.02567480829815484),
 (568, 0.1453095484297741),
 (569, 0.047457899787624956),
 (570, 0.07009996372327816),
 (571, 0.04317328917763455),
 (572, 0.10887588907733554),
 (573, 0.02122381799890044),
 (574, 0.023980056885558418),
 (575, 0.04604092555161308),
 (576, 0.0533380747062665),
 (577, 0.20343336780168372),
 (578, 0.03796631983009995),
 (579, 0.1453095484297741),
 (580, 0.024784079854830485),
 (581, 0.15819299929208316),
 (582, 0.2484013136974297),
 (583, 0.038482892144202245),
 (584, 0.08219949365267865),
 (585, 0.025070610528195012),
 (586, 0.04649905549752771),
 (587, 0.07271792483455794),
 (588, 0.02632490632463282),
 (589, 0.1178966237837789),
 (590, 0.03106848830006),
 (591, 0.06367145399670132),
 (592, 0.021586644588817275),
 (593, 0.0),
 (594, 0.050734628943184104),
 (595, 0.162746694241347),
 (596, 0.09299811099505542),
 (597, 0.06003002251876642),
 (598, 0.03771571432023571),
 (599, 0.027788500718836418),
 (600, 0.06974858324629157),
 (601, 0.033912921674035035),
 (602, 0.09208185110322616),
 (603, 0.055577001437672836),
 (604, 0.0685591170191061),
 (605, 0.02567480829815484),
 (606, 0.0),
 (607, 0.058531710827892644),
 (608, 0.0),
 (609, 0.04649905549752771),
 (610, 0.059053859535749265),
 (611, 0.02348556961505104),
 (612, 0.06367145399670132),
 (613, 0.036760731104690386),
 (614, 0.04901430813958719),
 (615, 0.06213697660012),
 (616, 0.03504998186163908),
 (617, 0.050734628943184104),
 (618, 0.08867021970429453),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06575959492214292),
 (622, 0.021586644588817275),
 (623, 0.0),
 (624, 0.10283867552865913),
 (625, 0.03163859985841663),
 (626, 0.08336550215650926),
 (627, 0.11028219331407116),
 (628, 0.0),
 (629, 0.04901430813958719),
 (630, 0.024239308278185982),
 (631, 0.04901430813958719),
 (632, 0.07798128673650545),
 (633, 0.02279803762937766),
 (634, 0.07521183158458504),
 (635, 0.06774581282657174),
 (636, 0.023728949893812478),
 (637, 0.024507154069793594),
 (638, 0.03427955850955305),
 (639, 0.0),
 (640, 0.06117355427146393),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10529962529853128),
 (644, 0.05134961659630968),
 (645, 0.04516387521771449),
 (646, 0.05405405405405406),
 (647, 0.04956815970966097),
 (648, 0.03106848830006),
 (649, 0.0),
 (650, 0.05264981264926564),
 (651, 0.0),
 (652, 0.04317328917763455),
 (653, 0.11028219331407116),
 (654, 0.10524566699352861),
 (655, 0.024239308278185982),
 (656, 0.0),
 (657, 0.035455197425947084),
 (658, 0.050141221056390024),
 (659, 0.025993762245501817),
 (660, 0.0949157995752499),
 (661, 0.16979054399120352),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06105625108726635),
 (665, 0.06906138832741962),
 (666, 0.050734628943184104),
 (667, 0.0),
 (668, 0.1371182340382122),
 (669, 0.036760731104690386),
 (670, 0.0178315737905373),
 (671, 0.06906138832741962),
 (672, 0.028618190351607124),
 (673, 0.020391184757154644),
 (674, 0.07194017065667525),
 (675, 0.04604092555161308),
 (676, 0.028194193721730043),
 (677, 0.02567480829815484),
 (678, 0.11810771907149853),
 (679, 0.0),
 (680, 0.07610194341477616),
 (681, 0.028194193721730043),
 (682, 0.02023611646290882),
 (683, 0.04901430813958719),
 (684, 0.0),
 (685, 0.03287979746107146),
 (686, 0.03163859985841663),
 (687, 0.106676149412533),
 (688, 0.04433510985214727),
 (689, 0.0),
 (690, 0.025367314471592052),
 (691, 0.06003002251876642),
 (692, 0.11083777463036817),
 (693, 0.03504998186163908),
 (694, 0.022167554926073633),
 (695, 0.0685591170191061),
 (696, 0.02177517781546711),
 (697, 0.0),
 (698, 0.04393747751637468),
 (699, 0.03874921291460643),
 (700, 0.029061909685954818),
 (701, 0.058123819371909635),
 (702, 0.02302046277580654),
 (703, 0.021049133398705722),
 (704, 0.06839411288813299),
 (705, 0.024784079854830485),
 (706, 0.022167554926073633),
 (707, 0.0),
 (708, 0.025367314471592052),
 (709, 0.020712325533373332),
 (710, 0.05894831189188944),
 (711, 0.0533380747062665),
 (712, 0.0),
 (713, 0.025993762245501817),
 (714, 0.0),
 (715, 0.10067340828210367),
 (716, 0.027399831217559546),
 (717, 0.0),
 (718, 0.04516387521771449),
 (719, 0.0),
 (720, 0.02702702702702703),
 (721, 0.03287979746107146),
 (722, 0.0),
 (723, 0.025070610528195012),
 (724, 0.024239308278185982),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03120812265889869),
 (728, 0.07352146220938079),
 (729, 0.04956815970966097),
 (730, 0.030660569226416797),
 (731, 0.0533380747062665),
 (732, 0.06906138832741962),
 (733, 0.06213697660011999),
 (734, 0.06774581282657174),
 (735, 0.06774581282657174),
 (736, 0.03001501125938321),
 (737, 0.07897471897389846),
 (738, 0.0),
 (739, 0.03874921291460643),
 (740, 0.11083777463036817),

In [53]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6] #we applied lambda bcoz from list we need sorting based on second column
#only top 5 similar movies

[(1216, 0.29061909685954823),
 (3730, 0.26401000024165),
 (507, 0.26130213378560535),
 (539, 0.2537477434955704),
 (2409, 0.2507061052819501)]

In [60]:
def recommend(movie):
    #to fetch index of movie in data
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:  #i is the whole tuple with index and cosine diatance of each of 5 movies
        print(new_df.iloc[i[0]].title)#printing by fetching through integer location of i[0]-->movie_index and column name is title

In [61]:
import pickle
pickle.dump(new_df,open('movies.pkl','wb'))

In [62]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [63]:
pickle.dump(similarity,open('similarity.pkl','wb'))